language: ruby
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - jruby-19mode
install: 'bundle install --deployment -j 4'
script:
  - "bundle exec rspec spec"
branches:
  only:
    - master
matrix:
  allow_failures:
    - rvm: jruby-19mode
